version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  setup-and-test:
    docker:
      - image: cimg/python:3.8.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install .
      - run:
          name: run tests
          command: pytest --cov=app --junitxml=test-results/junit.xml --cov-report xml:results.xml

      - store_test_results:
          path: test-results
      - codecov/upload:
          file: './results.xml'

workflows:
  build-and-test-workflow:
    jobs:
      - setup-and-test