version: 2.1

jobs:
  setup-and-test:
    docker:
      - image: cimg/python:3.8.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install .
      - run:
          name: run tests
          command: pytest --cov=app --junitxml=test-results/junit.xml --cov-report html:htmlcov

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov

workflows:
  build-and-test-workflow:
    jobs:
      - setup-and-test